language: go
go:
- '1.10'
- '1.11'
- tip
git:
  submodules: false
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
before_install:
  - go get -u github.com/Masterminds/glide
install:
  - git submodule update --init --recursive
  - glide --debug install
script:
- make ci